# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/test/Matrix_Operations

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/test/Matrix_Operations

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/test/Matrix_Operations/CMakeFiles /home/pi/test/Matrix_Operations/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/test/Matrix_Operations/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Assignment4_matrix_operation

# Build rule for target.
Assignment4_matrix_operation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Assignment4_matrix_operation
.PHONY : Assignment4_matrix_operation

# fast build rule for target.
Assignment4_matrix_operation/fast:
	$(MAKE) -f CMakeFiles/Assignment4_matrix_operation.dir/build.make CMakeFiles/Assignment4_matrix_operation.dir/build
.PHONY : Assignment4_matrix_operation/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Assignment4_matrix_operation.dir/build.make CMakeFiles/Assignment4_matrix_operation.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Assignment4_matrix_operation.dir/build.make CMakeFiles/Assignment4_matrix_operation.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Assignment4_matrix_operation.dir/build.make CMakeFiles/Assignment4_matrix_operation.dir/main.cpp.s
.PHONY : main.cpp.s

matrix.o: matrix.cpp.o

.PHONY : matrix.o

# target to build an object file
matrix.cpp.o:
	$(MAKE) -f CMakeFiles/Assignment4_matrix_operation.dir/build.make CMakeFiles/Assignment4_matrix_operation.dir/matrix.cpp.o
.PHONY : matrix.cpp.o

matrix.i: matrix.cpp.i

.PHONY : matrix.i

# target to preprocess a source file
matrix.cpp.i:
	$(MAKE) -f CMakeFiles/Assignment4_matrix_operation.dir/build.make CMakeFiles/Assignment4_matrix_operation.dir/matrix.cpp.i
.PHONY : matrix.cpp.i

matrix.s: matrix.cpp.s

.PHONY : matrix.s

# target to generate assembly for a file
matrix.cpp.s:
	$(MAKE) -f CMakeFiles/Assignment4_matrix_operation.dir/build.make CMakeFiles/Assignment4_matrix_operation.dir/matrix.cpp.s
.PHONY : matrix.cpp.s

mxm.o: mxm.cpp.o

.PHONY : mxm.o

# target to build an object file
mxm.cpp.o:
	$(MAKE) -f CMakeFiles/Assignment4_matrix_operation.dir/build.make CMakeFiles/Assignment4_matrix_operation.dir/mxm.cpp.o
.PHONY : mxm.cpp.o

mxm.i: mxm.cpp.i

.PHONY : mxm.i

# target to preprocess a source file
mxm.cpp.i:
	$(MAKE) -f CMakeFiles/Assignment4_matrix_operation.dir/build.make CMakeFiles/Assignment4_matrix_operation.dir/mxm.cpp.i
.PHONY : mxm.cpp.i

mxm.s: mxm.cpp.s

.PHONY : mxm.s

# target to generate assembly for a file
mxm.cpp.s:
	$(MAKE) -f CMakeFiles/Assignment4_matrix_operation.dir/build.make CMakeFiles/Assignment4_matrix_operation.dir/mxm.cpp.s
.PHONY : mxm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Assignment4_matrix_operation"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... matrix.o"
	@echo "... matrix.i"
	@echo "... matrix.s"
	@echo "... mxm.o"
	@echo "... mxm.i"
	@echo "... mxm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

